baseURL = "https://colourlessspearmint.github.io"
languageCode = "en-us"
title = "Ethan Marks"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    style = "github-dark"

[caches]
  [caches.images]
    dir = ':cacheDir/images'